# https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: public callable tasks/flows

    [tasks.default]
    description = "show list of public callable tasks"
    clear = true
    command = "cargo"
    args = ["make","--list-all-steps"]

    [tasks.dev]
    description = "cargo build development"
    clear = true
    dependencies = [
       # "lmake_version_from_date",
        "build-dev",
        "post-build",
    ]

    [tasks.release]
    description = "cargo build release"
    clear = true
    dependencies = [
        #"lmake_version_from_date",
        "build_release",
        "copy_pkg_to_webfolder",
        "post-build",
    ]

    [tasks.doc]
    description = "create docs from comments"
    clear = true
    dependencies = [
		"insert-readme",
        "cargo-doc",
		"doc-copy",
    ]
# endregion


[tasks.build-dev]
clear = true
private = true
description = "build wasm in dev mode"
command = "wasm-pack"
args = ["build", "--target", "web","--dev"]


    [tasks.publish]
    description = "publish the webfolder to google vm"
    # First copies the content of /efrro_form_c_json/webfolder to //googlecloud/ folder and then to google vm with use of sshagent."
    workspace = false
    clear = true
    # backslash is the escape character for all other special characters.
    # and then another time I have to escape the backslash. So 4 backslash for one backslash.
    script = [
        "rsync -avz --delete-after /home/luciano/rustprojects/efrro_form_c_json/webfolder/ /home/luciano/rustprojects/googlecloud/var/www/html/efrro_form_c_json/",
		"rsync -avz --delete-after /home/luciano/rustprojects/efrro_form_c_json_hostels/hostels/ /home/luciano/rustprojects/googlecloud/var/www/html/efrro_form_c_json/hostels/",
        "rsync -e ssh -avz --delete-after /home/luciano/rustprojects/googlecloud/var/www/html/efrro_form_c_json/ luciano_bestia@34.87.17.103:/var/www/html/efrro_form_c_json_beta/",
    ]

    [tasks.sshadd]
    description = "adds identity to ssh-agent for git and publish operations"
    workspace = false
    clear = true
    script = [
        "ssh-add /home/luciano/.ssh/luciano_googlecloud",
        "ssh-add /home/luciano/.ssh/lucianobestia_mac",
        "ssh-add -l",
    ]

[tasks.post-build]
clear = true
private = true
description = "open browser and start http server"
script = [
    "alias chrome=\"/mnt/c/Program\\ Files\\ \\(x86\\)/Google/Chrome/Application/chrome.exe\"",
    "chrome http://127.0.0.1:8086/webfolder?id=sturmfrei_goa", 
    #"start \"firefox\" \"C:\\Program Files\\Mozilla Firefox\\firefox.exe\" 127.0.0.1:8086",
    "basic-http-server -a 127.0.0.1:8086",
]

[tasks.insert-readme]
clear = true
private = true
description = "copy the content of readme.md into *.rs comments (for the docs)"
script= ["../utils_linux/lmake_readme"]

[tasks.cargo-doc]
clear = true
private = true
description = "call cargo doc"
command="cargo"
args=["doc","--no-deps","--document-private-items","--open"]

[tasks.doc-copy]
clear = true
private = true
description = "copy doc folder as docs (out of folder target), so it can be git comitted"
script = [
    "\\rsync -avz --delete-after ~/rustprojects/efrro_form_c_json/target/doc/*  ~/rustprojects/efrro_form_c_json/docs/"
]

[tasks.lmake_version_from_date]
clear = true
private = true
description = "in cargo.toml change version to today date"
script= ["../utils_linux/lmake_version_from_date"]

[tasks.build_release]
description = "build for release"
clear = true
private = true
command = "wasm-pack"
args = ["build","--target", "web","--release", "--no-typescript"]

[tasks.copy_pkg_to_webfolder]
description = "copy wasm pkg to webfolder"
clear = true
private = true
script = [
    "\\rsync -avz --delete-after ~/rustprojects/efrro_form_c_json/pkg/  ~/rustprojects/efrro_form_c_json/webfolder/pkg/",
]

